# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
# Import torch
import torch

# Create random tensor
tensor_1 = torch.rand(7, 7)
tensor_1


tensor([[0.0183, 0.3969, 0.4831, 0.3453, 0.9240, 0.3023, 0.3455],
        [0.2880, 0.7617, 0.5330, 0.1915, 0.4756, 0.1245, 0.9843],
        [0.7078, 0.7105, 0.8498, 0.1069, 0.7500, 0.2059, 0.6150],
        [0.5606, 0.4238, 0.0574, 0.9024, 0.9425, 0.8243, 0.2052],
        [0.2739, 0.2472, 0.0116, 0.8491, 0.0743, 0.9495, 0.0256],
        [0.5867, 0.3283, 0.5033, 0.9021, 0.2621, 0.8601, 0.3470],
        [0.2782, 0.6729, 0.9154, 0.6784, 0.6903, 0.8761, 0.9117]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensor_2 = torch.rand(1, 7)
# Perform matrix multiplication
torch.mm(tensor_1, tensor_2.T)

tensor([[1.0377],
        [1.1406],
        [1.4143],
        [1.6564],
        [1.1135],
        [1.5275],
        [1.9551]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(1,7)
# Matrix multiply tensors
torch.mm(tensor_1, tensor_2.T), torch.mm(tensor_1, tensor_2.T).shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [22]:
# Set random seed on the GPU
GPU_RANDOM_SEED = 1234
torch.cuda.manual_seed(GPU_RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [26]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(2, 3).to(device)
torch.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(2, 3).to(device)
print(f"Device: {device}")
print(tensor_1)
print(tensor_2)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [35]:
# Perform matmul on tensor_A and tensor_B
## Solution 1
torch.mm(tensor_1, tensor_2.reshape(3, 2)), torch.mm(tensor_1, tensor_2.reshape(3, 2)).shape
## Solution 2
tensor_3 = torch.mm(tensor_1, tensor_2.T)
tensor_3, tensor_3.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [38]:
# Find max
print(f"Maximum = {torch.max(tensor_3)}")

# Find min
print(f"Minimum = {torch.min(tensor_3)}")

Maximum = 0.628727912902832
Minimum = 0.21611443161964417


### 9. Find the maximum and minimum index values of the output of 7.

In [40]:
# Find arg max
print(f"Argmax = {torch.argmax(tensor_3)}")

# Find arg min
print(f"Argmin = {torch.argmin(tensor_3)}")

Argmax = 3
Argmin = 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
R_SEED = 7

# Create random tensor
torch.manual_seed(R_SEED)
tensor_1 = torch.rand(1, 1, 1, 10)
# Remove single dimensions
torch.manual_seed(R_SEED)
tensor_2 = torch.squeeze(tensor_1)
tensor_2, tensor_2.shape
# Print out tensors and their shapes
print(tensor_1, tensor_1.shape)
print(tensor_2, tensor_2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
